---
 #tasks file for prometheus-grafana
- name: Create directory for Prometheus server
  file:
    path: /{{ monitoring_path }}/prometheus_server
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create directory for Prometheus confing
  file:
    path: /{{ monitoring_path }}/prometheus_server/prometheus
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Copy Grafana files
  copy:
    src: "{{ role_path }}/files/grafana/provisioning"
    dest: "{{ monitoring_path }}/prometheus_server/grafana"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Copy templates
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "{{ user }}"
   group: "{{ group }}"
  with_items:
      - {src: '{{ role_path }}/templates/env.j2', dest: '{{ monitoring_path }}/prometheus_server/.env'}
      - {src: '{{ role_path }}/templates/datasource.j2', dest: '{{ monitoring_path }}/prometheus_server/grafana/provisioning/datasources/datasource.yml'}

- name: Copy docker-compose template for RHEL OS
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "{{ user }}"
   group: "{{ group }}"
  with_items:
      - {src: '{{ role_path }}/templates/monitoring_rhel.j2', dest: '{{ monitoring_path }}/prometheus_server/monitoring.yml'}
  when: ansible_os_family == "RedHat"

- name: Copy docker-compose template for Debian OS
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "{{ user }}"
   group: "{{ group }}"
  with_items:
      - {src: '{{ role_path }}/templates/monitoring_debian.j2', dest: '{{ monitoring_path }}/prometheus_server/monitoring.yml'}
  when: ansible_os_family == "Debian"

- name: Print cadv_servers to prometheus.yml file
  debug:
    msg: "{{ item }}"
  loop: "{{ cadv_servers }}"
- name: Copy prometheus template to monitoring server
  template:
    src={{ role_path }}/templates/prometheus.j2
    dest={{ monitoring_path }}/prometheus_server/prometheus/prometheus.yml
  notify:
        - Restart prometheus

- name: Print nod_exp_servers to prometheus.yml file
  debug:
    msg: "{{ item }}"
  loop: "{{ nod_exp_servers }}"
- name: Copy prometheus template to monitoring server
  template:
    src={{ role_path }}/templates/prometheus.j2
    dest={{ monitoring_path }}/prometheus_server/prometheus/prometheus.yml
  notify:
        - Restart prometheus

- name: Run moniroting server in Docker container
  shell: docker-compose -f {{ monitoring_path }}/prometheus_server/monitoring.yml up -d
